from unittest import TestCase
from unittest.mock import patch, Mock

from GetRepo import get_user_info

class TestGetRepo(TestCase):
    @patch('GetRepo.get_repo_info')
    def test_get_repo_info(self, get_repo_info):
        get_repo_info.return_value = [
            {
                'id': 120936504,
                'name': 'test1',
                'full_name': 'ywang567/test1',
                'owner': {'login': 'ywang567',
                'id': 35854285,
                'avatar_url': 'https://avatars3.githubusercontent.com/u/35854285?v=4',
                'gravatar_id': '',
                'url': 'https://api.github.com/users/ywang567',
                'html_url': 'https://github.com/ywang567',
                'followers_url': 'https://api.github.com/users/ywang567/followers',
                'following_url': 'https://api.github.com/users/ywang567/following{/other_user}',
                'gists_url': 'https://api.github.com/users/ywang567/gists{/gist_id}',
                'starred_url': 'https://api.github.com/users/ywang567/starred{/owner}{/repo}',
                'subscriptions_url': 'https://api.github.com/users/ywang567/subscriptions',
                'organizations_url': 'https://api.github.com/users/ywang567/orgs',
                'repos_url': 'https://api.github.com/users/ywang567/repos',
                'events_url': 'https://api.github.com/users/ywang567/events{/privacy}',
                'received_events_url': 'https://api.github.com/users/ywang567/received_events',
                'type': 'User',
                'site_admin': False},
                'private': False,
                'html_url': 'https://github.com/ywang567/test1',
                'description': None,
                'fork': False,
                'url': 'https://api.github.com/repos/ywang567/test1',
                'forks_url': 'https://api.github.com/repos/ywang567/test1/forks',
                'keys_url': 'https://api.github.com/repos/ywang567/test1/keys{/key_id}',
                'collaborators_url': 'https://api.github.com/repos/ywang567/test1/collaborators{/collaborator}',
                'teams_url': 'https://api.github.com/repos/ywang567/test1/teams',
                'hooks_url': 'https://api.github.com/repos/ywang567/test1/hooks',
                'issue_events_url': 'https://api.github.com/repos/ywang567/test1/issues/events{/number}',
                'events_url': 'https://api.github.com/repos/ywang567/test1/events',
                'assignees_url': 'https://api.github.com/repos/ywang567/test1/assignees{/user}',
                'branches_url': 'https://api.github.com/repos/ywang567/test1/branches{/branch}',
                'tags_url': 'https://api.github.com/repos/ywang567/test1/tags',
                'blobs_url': 'https://api.github.com/repos/ywang567/test1/git/blobs{/sha}',
                'git_tags_url': 'https://api.github.com/repos/ywang567/test1/git/tags{/sha}',
                'git_refs_url': 'https://api.github.com/repos/ywang567/test1/git/refs{/sha}',
                'trees_url': 'https://api.github.com/repos/ywang567/test1/git/trees{/sha}',
                'statuses_url': 'https://api.github.com/repos/ywang567/test1/statuses/{sha}',
                'languages_url': 'https://api.github.com/repos/ywang567/test1/languages',
                'stargazers_url': 'https://api.github.com/repos/ywang567/test1/stargazers',
                'contributors_url': 'https://api.github.com/repos/ywang567/test1/contributors',
                'subscribers_url': 'https://api.github.com/repos/ywang567/test1/subscribers',
                'subscription_url': 'https://api.github.com/repos/ywang567/test1/subscription',
                'commits_url': 'https://api.github.com/repos/ywang567/test1/commits{/sha}',
                'git_commits_url': 'https://api.github.com/repos/ywang567/test1/git/commits{/sha}',
                'comments_url': 'https://api.github.com/repos/ywang567/test1/comments{/number}',
                'issue_comment_url': 'https://api.github.com/repos/ywang567/test1/issues/comments{/number}',
                'contents_url': 'https://api.github.com/repos/ywang567/test1/contents/{+path}',
                'compare_url': 'https://api.github.com/repos/ywang567/test1/compare/{base}...{head}',
                'merges_url': 'https://api.github.com/repos/ywang567/test1/merges',
                'archive_url': 'https://api.github.com/repos/ywang567/test1/{archive_format}{/ref}',
                'downloads_url': 'https://api.github.com/repos/ywang567/test1/downloads',
                'issues_url': 'https://api.github.com/repos/ywang567/test1/issues{/number}',
                'pulls_url': 'https://api.github.com/repos/ywang567/test1/pulls{/number}',
                'milestones_url': 'https://api.github.com/repos/ywang567/test1/milestones{/number}',
                'notifications_url': 'https://api.github.com/repos/ywang567/test1/notifications{?since,all,participating}',
                'labels_url': 'https://api.github.com/repos/ywang567/test1/labels{/name}',
                'releases_url': 'https://api.github.com/repos/ywang567/test1/releases{/id}',
                'deployments_url': 'https://api.github.com/repos/ywang567/test1/deployments',
                'created_at': '2018-02-09T17:42:05Z',
                'updated_at': '2018-02-09T17:43:01Z',
                'pushed_at': '2018-02-09T17:42:30Z',
                'git_url': 'git://github.com/ywang567/test1.git',
                'ssh_url': 'git@github.com:ywang567/test1.git',
                'clone_url': 'https://github.com/ywang567/test1.git',
                'svn_url': 'https://github.com/ywang567/test1',
                'homepage': None,
                'size': 1,
                'stargazers_count': 0,
                'watchers_count': 0,
                'language': None,
                'has_issues': True,
                'has_projects': True,
                'has_downloads': True,
                'has_wiki': True,
                'has_pages': False,
                'forks_count': 0,
                'mirror_url': None,
                'archived': False,
                'open_issues_count': 0,
                'license': None,
                'forks': 0,
                'open_issues': 0,
                'watchers': 0,
                'default_branch': 'master'
            }, 
            {
                'id': 120936567,
                'name': 'test2',
                'full_name': 'ywang567/test2',
                'owner': {'login': 'ywang567',
                'id': 35854285,
                'avatar_url': 'https://avatars3.githubusercontent.com/u/35854285?v=4',
                'gravatar_id': '',
                'url': 'https://api.github.com/users/ywang567',
                'html_url': 'https://github.com/ywang567',
                'followers_url': 'https://api.github.com/users/ywang567/followers',
                'following_url': 'https://api.github.com/users/ywang567/following{/other_user}',
                'gists_url': 'https://api.github.com/users/ywang567/gists{/gist_id}',
                'starred_url': 'https://api.github.com/users/ywang567/starred{/owner}{/repo}',
                'subscriptions_url': 'https://api.github.com/users/ywang567/subscriptions',
                'organizations_url': 'https://api.github.com/users/ywang567/orgs',
                'repos_url': 'https://api.github.com/users/ywang567/repos',
                'events_url': 'https://api.github.com/users/ywang567/events{/privacy}',
                'received_events_url': 'https://api.github.com/users/ywang567/received_events',
                'type': 'User',
                'site_admin': False},
                'private': False,
                'html_url': 'https://github.com/ywang567/test2',
                'description': None,
                'fork': False,
                'url': 'https://api.github.com/repos/ywang567/test2',
                'forks_url': 'https://api.github.com/repos/ywang567/test2/forks',
                'keys_url': 'https://api.github.com/repos/ywang567/test2/keys{/key_id}',
                'collaborators_url': 'https://api.github.com/repos/ywang567/test2/collaborators{/collaborator}',
                'teams_url': 'https://api.github.com/repos/ywang567/test2/teams',
                'hooks_url': 'https://api.github.com/repos/ywang567/test2/hooks',
                'issue_events_url': 'https://api.github.com/repos/ywang567/test2/issues/events{/number}',
                'events_url': 'https://api.github.com/repos/ywang567/test2/events',
                'assignees_url': 'https://api.github.com/repos/ywang567/test2/assignees{/user}',
                'branches_url': 'https://api.github.com/repos/ywang567/test2/branches{/branch}',
                'tags_url': 'https://api.github.com/repos/ywang567/test2/tags',
                'blobs_url': 'https://api.github.com/repos/ywang567/test2/git/blobs{/sha}',
                'git_tags_url': 'https://api.github.com/repos/ywang567/test2/git/tags{/sha}',
                'git_refs_url': 'https://api.github.com/repos/ywang567/test2/git/refs{/sha}',
                'trees_url': 'https://api.github.com/repos/ywang567/test2/git/trees{/sha}',
                'statuses_url': 'https://api.github.com/repos/ywang567/test2/statuses/{sha}',
                'languages_url': 'https://api.github.com/repos/ywang567/test2/languages',
                'stargazers_url': 'https://api.github.com/repos/ywang567/test2/stargazers',
                'contributors_url': 'https://api.github.com/repos/ywang567/test2/contributors',
                'subscribers_url': 'https://api.github.com/repos/ywang567/test2/subscribers',
                'subscription_url': 'https://api.github.com/repos/ywang567/test2/subscription',
                'commits_url': 'https://api.github.com/repos/ywang567/test2/commits{/sha}',
                'git_commits_url': 'https://api.github.com/repos/ywang567/test2/git/commits{/sha}',
                'comments_url': 'https://api.github.com/repos/ywang567/test2/comments{/number}',
                'issue_comment_url': 'https://api.github.com/repos/ywang567/test2/issues/comments{/number}',
                'contents_url': 'https://api.github.com/repos/ywang567/test2/contents/{+path}',
                'compare_url': 'https://api.github.com/repos/ywang567/test2/compare/{base}...{head}',
                'merges_url': 'https://api.github.com/repos/ywang567/test2/merges',
                'archive_url': 'https://api.github.com/repos/ywang567/test2/{archive_format}{/ref}',
                'downloads_url': 'https://api.github.com/repos/ywang567/test2/downloads',
                'issues_url': 'https://api.github.com/repos/ywang567/test2/issues{/number}',
                'pulls_url': 'https://api.github.com/repos/ywang567/test2/pulls{/number}',
                'milestones_url': 'https://api.github.com/repos/ywang567/test2/milestones{/number}',
                'notifications_url': 'https://api.github.com/repos/ywang567/test2/notifications{?since,all,participating}',
                'labels_url': 'https://api.github.com/repos/ywang567/test2/labels{/name}',
                'releases_url': 'https://api.github.com/repos/ywang567/test2/releases{/id}',
                'deployments_url': 'https://api.github.com/repos/ywang567/test2/deployments',
                'created_at': '2018-02-09T17:42:42Z',
                'updated_at': '2018-02-09T17:43:13Z',
                'pushed_at': '2018-02-09T17:43:24Z',
                'git_url': 'git://github.com/ywang567/test2.git',
                'ssh_url': 'git@github.com:ywang567/test2.git',
                'clone_url': 'https://github.com/ywang567/test2.git',
                'svn_url': 'https://github.com/ywang567/test2',
                'homepage': None,
                'size': 1,
                'stargazers_count': 0,
                'watchers_count': 0,
                'language': None,
                'has_issues': True,
                'has_projects': True,
                'has_downloads': True,
                'has_wiki': True,
                'has_pages': False,
                'forks_count': 0,
                'mirror_url': None,
                'archived': False,
                'open_issues_count': 0,
                'license': None,
                'forks': 0,
                'open_issues': 0,
                'watchers': 0,
                'default_branch': 'master'
            }, 
            {
                'id': 119112523,
                'name': 'Triangle567',
                'full_name': 'ywang567/Triangle567',
                'owner': {'login': 'ywang567',
                'id': 35854285,
                'avatar_url': 'https://avatars3.githubusercontent.com/u/35854285?v=4',
                'gravatar_id': '',
                'url': 'https://api.github.com/users/ywang567',
                'html_url': 'https://github.com/ywang567',
                'followers_url': 'https://api.github.com/users/ywang567/followers',
                'following_url': 'https://api.github.com/users/ywang567/following{/other_user}',
                'gists_url': 'https://api.github.com/users/ywang567/gists{/gist_id}',
                'starred_url': 'https://api.github.com/users/ywang567/starred{/owner}{/repo}',
                'subscriptions_url': 'https://api.github.com/users/ywang567/subscriptions',
                'organizations_url': 'https://api.github.com/users/ywang567/orgs',
                'repos_url': 'https://api.github.com/users/ywang567/repos',
                'events_url': 'https://api.github.com/users/ywang567/events{/privacy}',
                'received_events_url': 'https://api.github.com/users/ywang567/received_events',
                'type': 'User',
                'site_admin': False},
                'private': False,
                'html_url': 'https://github.com/ywang567/Triangle567',
                'description': None,
                'fork': False,
                'url': 'https://api.github.com/repos/ywang567/Triangle567',
                'forks_url': 'https://api.github.com/repos/ywang567/Triangle567/forks',
                'keys_url': 'https://api.github.com/repos/ywang567/Triangle567/keys{/key_id}',
                'collaborators_url': 'https://api.github.com/repos/ywang567/Triangle567/collaborators{/collaborator}',
                'teams_url': 'https://api.github.com/repos/ywang567/Triangle567/teams',
                'hooks_url': 'https://api.github.com/repos/ywang567/Triangle567/hooks',
                'issue_events_url': 'https://api.github.com/repos/ywang567/Triangle567/issues/events{/number}',
                'events_url': 'https://api.github.com/repos/ywang567/Triangle567/events',
                'assignees_url': 'https://api.github.com/repos/ywang567/Triangle567/assignees{/user}',
                'branches_url': 'https://api.github.com/repos/ywang567/Triangle567/branches{/branch}',
                'tags_url': 'https://api.github.com/repos/ywang567/Triangle567/tags',
                'blobs_url': 'https://api.github.com/repos/ywang567/Triangle567/git/blobs{/sha}',
                'git_tags_url': 'https://api.github.com/repos/ywang567/Triangle567/git/tags{/sha}',
                'git_refs_url': 'https://api.github.com/repos/ywang567/Triangle567/git/refs{/sha}',
                'trees_url': 'https://api.github.com/repos/ywang567/Triangle567/git/trees{/sha}',
                'statuses_url': 'https://api.github.com/repos/ywang567/Triangle567/statuses/{sha}',
                'languages_url': 'https://api.github.com/repos/ywang567/Triangle567/languages',
                'stargazers_url': 'https://api.github.com/repos/ywang567/Triangle567/stargazers',
                'contributors_url': 'https://api.github.com/repos/ywang567/Triangle567/contributors',
                'subscribers_url': 'https://api.github.com/repos/ywang567/Triangle567/subscribers',
                'subscription_url': 'https://api.github.com/repos/ywang567/Triangle567/subscription',
                'commits_url': 'https://api.github.com/repos/ywang567/Triangle567/commits{/sha}',
                'git_commits_url': 'https://api.github.com/repos/ywang567/Triangle567/git/commits{/sha}',
                'comments_url': 'https://api.github.com/repos/ywang567/Triangle567/comments{/number}',
                'issue_comment_url': 'https://api.github.com/repos/ywang567/Triangle567/issues/comments{/number}',
                'contents_url': 'https://api.github.com/repos/ywang567/Triangle567/contents/{+path}',
                'compare_url': 'https://api.github.com/repos/ywang567/Triangle567/compare/{base}...{head}',
                'merges_url': 'https://api.github.com/repos/ywang567/Triangle567/merges',
                'archive_url': 'https://api.github.com/repos/ywang567/Triangle567/{archive_format}{/ref}',
                'downloads_url': 'https://api.github.com/repos/ywang567/Triangle567/downloads',
                'issues_url': 'https://api.github.com/repos/ywang567/Triangle567/issues{/number}',
                'pulls_url': 'https://api.github.com/repos/ywang567/Triangle567/pulls{/number}',
                'milestones_url': 'https://api.github.com/repos/ywang567/Triangle567/milestones{/number}',
                'notifications_url': 'https://api.github.com/repos/ywang567/Triangle567/notifications{?since,all,participating}',
                'labels_url': 'https://api.github.com/repos/ywang567/Triangle567/labels{/name}',
                'releases_url': 'https://api.github.com/repos/ywang567/Triangle567/releases{/id}',
                'deployments_url': 'https://api.github.com/repos/ywang567/Triangle567/deployments',
                'created_at': '2018-01-26T23:01:37Z',
                'updated_at': '2018-01-26T23:01:37Z',
                'pushed_at': '2018-01-26T23:01:39Z',
                'git_url': 'git://github.com/ywang567/Triangle567.git',
                'ssh_url': 'git@github.com:ywang567/Triangle567.git',
                'clone_url': 'https://github.com/ywang567/Triangle567.git',
                'svn_url': 'https://github.com/ywang567/Triangle567',
                'homepage': None,
                'size': 0,
                'stargazers_count': 0,
                'watchers_count': 0,
                'language': None,
                'has_issues': True,
                'has_projects': True,
                'has_downloads': True,
                'has_wiki': True,
                'has_pages': False,
                'forks_count': 0,
                'mirror_url': None,
                'archived': False,
                'open_issues_count': 0,
                'license': None,
                'forks': 0,
                'open_issues': 0,
                'watchers': 0,
                'default_branch': 'master'
            }
        ]
        response = get_repo_info()
        self.assertIsNotNone(response)
        self.assertIsInstance(response[0], dict)
    
    @patch('GetRepo.get_commit_info')
    def test_get_commit_info(self, get_commit_info):
        get_commit_info.return_value = [
            [
                {'sha': '495eabaf4727e2d26461beaedc21d91c68b24f5d', 'commit': {'author': {'name': 'ywang567', 'email': '35854285+ywang567@users.noreply.github.com', 'date': '2018-02-09T17:42:28Z'}, 'committer': {'name': 'GitHub', 'email': 'noreply@github.com', 'date': '2018-02-09T17:42:28Z'}, 'message': 'Create rwa', 'tree': 
                {'sha': '2e1fd6a8af55225277dc867a24404bca4d8097cc', 'url': 'https://api.github.com/repos/ywang567/test1/git/trees/2e1fd6a8af55225277dc867a24404bca4d8097cc'}, 'url': 'https://api.github.com/repos/ywang567/test1/git/commits/495eabaf4727e2d26461beaedc21d91c68b24f5d', 'comment_count': 0, 'verification': {'verified': True, 'reason': 'valid', 'signature': '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJafd2ECRBK7hj4Ov3rIwAAdHIIADteACiNhRQ66DXIrLZqYp+S\nMLvWu63Z71OV2K9Q2XPt9Y3r5IACK/PZzRdJck61vNRgk06VcBtwVBfdxB0NhLZv\nYafaEaZOEhUEEavUTDanP1lO3CD1sv+xrJVuGAyecD0nopg9l0v/iRnATwZkT2M4\n7fRFBpSvwaaoqHnh9LK3qJVfOq30KNnqLOrvDSkmI2je6N+QZy8MEyrkLjDdxwBJ\nanHm5qqtUWwaSKymOjFEZcBqZCggo0FXv8Ez7QAY6RPJ2D2aPGFEZXyIx4xem0wS\n2YLK5P6+BRGbnpaVhm4qWkCr9LOvhPxMV9ysmhg1cqVIxgtqWR0L/u8GuZQidSE=\n=5dtA\n-----END PGP SIGNATURE-----\n', 'payload': 'tree 2e1fd6a8af55225277dc867a24404bca4d8097cc\nparent b113d08ca7b13b16b6331ff803a16b0957a8f318\nauthor ywang567 <35854285+ywang567@users.noreply.github.com> 1518198148 -0500\ncommitter GitHub <noreply@github.com> 1518198148 -0500\n\nCreate rwa'}}, 'url': 'https://api.github.com/repos/ywang567/test1/commits/495eabaf4727e2d26461beaedc21d91c68b24f5d', 'html_url': 'https://github.com/ywang567/test1/commit/495eabaf4727e2d26461beaedc21d91c68b24f5d', 'comments_url': 'https://api.github.com/repos/ywang567/test1/commits/495eabaf4727e2d26461beaedc21d91c68b24f5d/comments', 'author': {'login': 'ywang567', 'id': 35854285, 'avatar_url': 'https://avatars3.githubusercontent.com/u/35854285?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ywang567', 'html_url': 'https://github.com/ywang567', 'followers_url': 'https://api.github.com/users/ywang567/followers', 'following_url': 'https://api.github.com/users/ywang567/following{/other_user}', 'gists_url': 'https://api.github.com/users/ywang567/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ywang567/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ywang567/subscriptions', 'organizations_url': 'https://api.github.com/users/ywang567/orgs', 'repos_url': 'https://api.github.com/users/ywang567/repos', 'events_url': 'https://api.github.com/users/ywang567/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ywang567/received_events', 'type': 'User', 'site_admin': False}, 'committer': {'login': 'web-flow', 'id': 19864447, 'avatar_url': 'https://avatars3.githubusercontent.com/u/19864447?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/web-flow', 'html_url': 'https://github.com/web-flow', 'followers_url': 'https://api.github.com/users/web-flow/followers', 'following_url': 'https://api.github.com/users/web-flow/following{/other_user}', 'gists_url': 'https://api.github.com/users/web-flow/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/web-flow/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/web-flow/subscriptions', 'organizations_url': 'https://api.github.com/users/web-flow/orgs', 'repos_url': 'https://api.github.com/users/web-flow/repos', 'events_url': 'https://api.github.com/users/web-flow/events{/privacy}', 'received_events_url': 'https://api.github.com/users/web-flow/received_events', 'type': 'User', 'site_admin': False}, 'parents': [
                {'sha': 'b113d08ca7b13b16b6331ff803a16b0957a8f318', 'url': 'https://api.github.com/repos/ywang567/test1/commits/b113d08ca7b13b16b6331ff803a16b0957a8f318', 'html_url': 'https://github.com/ywang567/test1/commit/b113d08ca7b13b16b6331ff803a16b0957a8f318'}]}, 
                {'sha': 'b113d08ca7b13b16b6331ff803a16b0957a8f318', 'commit': {'author': {'name': 'ywang567', 'email': '35854285+ywang567@users.noreply.github.com', 'date': '2018-02-09T17:42:19Z'}, 'committer': {'name': 'GitHub', 'email': 'noreply@github.com', 'date': '2018-02-09T17:42:19Z'}, 'message': 'Create new1', 'tree': 
                {'sha': '57e6f92d0545dc26c192b216be5e938f6eb2691f', 'url': 'https://api.github.com/repos/ywang567/test1/git/trees/57e6f92d0545dc26c192b216be5e938f6eb2691f'}, 'url': 'https://api.github.com/repos/ywang567/test1/git/commits/b113d08ca7b13b16b6331ff803a16b0957a8f318', 'comment_count': 0, 'verification': {'verified': True, 'reason': 'valid', 'signature': '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJafd17CRBK7hj4Ov3rIwAAdHIIAGpe1ZLL1yTg2dFSO49Fyq/0\nkd7Sk17oCGPsdQpOtEvQ3YVLXhszAhNCEJ9xN/Ta+KqpG0oFDfLIxOnSVYvFk/HJ\nxtGiTXPeQTPnPoc+bdJaAloJq2/rgYK3c7qylHT1RmKXdA073ws4ac/43/A1zKFz\nr9zl0gOBFGczk8CZA35wWdV6dEvGyN1QpiYPgK5fXiwri+TZj+c6WPf+XQK82AfR\nOz16Uwi1w1gwnv/7lnWxxLIW0M3qcy7ChiWeFP+rxfWXBxSNzfSProYUYU1wO8d+\ncRg2fxwYgY7YxrGLHtLgI0pCLWnx+avInez7vy4rALbaig/47awq5g7YmvUh5sk=\n=cPuu\n-----END PGP SIGNATURE-----\n', 'payload': 'tree 57e6f92d0545dc26c192b216be5e938f6eb2691f\nparent 56802f0ad5b1b3aa5c3e62b0164f3c644f6f7e5d\nauthor ywang567 <35854285+ywang567@users.noreply.github.com> 1518198139 -0500\ncommitter GitHub <noreply@github.com> 1518198139 -0500\n\nCreate new1'}}, 'url': 'https://api.github.com/repos/ywang567/test1/commits/b113d08ca7b13b16b6331ff803a16b0957a8f318', 'html_url': 'https://github.com/ywang567/test1/commit/b113d08ca7b13b16b6331ff803a16b0957a8f318', 'comments_url': 'https://api.github.com/repos/ywang567/test1/commits/b113d08ca7b13b16b6331ff803a16b0957a8f318/comments', 'author': {'login': 'ywang567', 'id': 35854285, 'avatar_url': 'https://avatars3.githubusercontent.com/u/35854285?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ywang567', 'html_url': 'https://github.com/ywang567', 'followers_url': 'https://api.github.com/users/ywang567/followers', 'following_url': 'https://api.github.com/users/ywang567/following{/other_user}', 'gists_url': 'https://api.github.com/users/ywang567/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ywang567/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ywang567/subscriptions', 'organizations_url': 'https://api.github.com/users/ywang567/orgs', 'repos_url': 'https://api.github.com/users/ywang567/repos', 'events_url': 'https://api.github.com/users/ywang567/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ywang567/received_events', 'type': 'User', 'site_admin': False}, 'committer': {'login': 'web-flow', 'id': 19864447, 'avatar_url': 'https://avatars3.githubusercontent.com/u/19864447?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/web-flow', 'html_url': 'https://github.com/web-flow', 'followers_url': 'https://api.github.com/users/web-flow/followers', 'following_url': 'https://api.github.com/users/web-flow/following{/other_user}', 'gists_url': 'https://api.github.com/users/web-flow/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/web-flow/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/web-flow/subscriptions', 'organizations_url': 'https://api.github.com/users/web-flow/orgs', 'repos_url': 'https://api.github.com/users/web-flow/repos', 'events_url': 'https://api.github.com/users/web-flow/events{/privacy}', 'received_events_url': 'https://api.github.com/users/web-flow/received_events', 'type': 'User', 'site_admin': False}, 'parents': [
                {'sha': '56802f0ad5b1b3aa5c3e62b0164f3c644f6f7e5d', 'url': 'https://api.github.com/repos/ywang567/test1/commits/56802f0ad5b1b3aa5c3e62b0164f3c644f6f7e5d', 'html_url': 'https://github.com/ywang567/test1/commit/56802f0ad5b1b3aa5c3e62b0164f3c644f6f7e5d'}]}, 
                {'sha': '56802f0ad5b1b3aa5c3e62b0164f3c644f6f7e5d', 'commit': {'author': {'name': 'ywang567', 'email': '35854285+ywang567@users.noreply.github.com', 'date': '2018-02-09T17:42:05Z'}, 'committer': {'name': 'GitHub', 'email': 'noreply@github.com', 'date': '2018-02-09T17:42:05Z'}, 'message': 'Initial commit', 'tree': 
                {'sha': '6219f445ba5aa1f91923ff8c2bab03cda8e69f83', 'url': 'https://api.github.com/repos/ywang567/test1/git/trees/6219f445ba5aa1f91923ff8c2bab03cda8e69f83'}, 'url': 'https://api.github.com/repos/ywang567/test1/git/commits/56802f0ad5b1b3aa5c3e62b0164f3c644f6f7e5d', 'comment_count': 0, 'verification': {'verified': True, 'reason': 'valid', 'signature': '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJafd1tCRBK7hj4Ov3rIwAAdHIIAD3F0r/5Q2mcdg95vXwaIHEG\nopVHsaxB7mvqaYbIQmhgDjAFzqwNOr+Lv7xEiNfOK6C659HxaQv+9+79q1xeJCVV\njoLdgmDrrwgPw0HbSacgXe+R9pyvSmuh+xU+WuMFaD0yBZlYFBgK40LBslJeq+AX\nMcpdaZ+lpGWl7RXeblLuDJ2Vu3I8YPP0GZ7z7DSz48BsjWFajyMRA6cbQTzTaNMO\nn5XNUcpt3OY1Rrd4ZXBTdjpNflqxiFGhiYQdfHOKHdfWULliKHHl/SXhxRkqkjbX\nTjj5pWqsTsD+e8JFjmqAfc62wVVrYInM3poFJYN8sZ97fO2uwd3weZ3QSnEU8ps=\n=mr9t\n-----END PGP SIGNATURE-----\n', 'payload': 'tree 6219f445ba5aa1f91923ff8c2bab03cda8e69f83\nauthor ywang567 <35854285+ywang567@users.noreply.github.com> 1518198125 -0500\ncommitter GitHub <noreply@github.com> 1518198125 -0500\n\nInitial commit'}}, 'url': 'https://api.github.com/repos/ywang567/test1/commits/56802f0ad5b1b3aa5c3e62b0164f3c644f6f7e5d', 'html_url': 'https://github.com/ywang567/test1/commit/56802f0ad5b1b3aa5c3e62b0164f3c644f6f7e5d', 'comments_url': 'https://api.github.com/repos/ywang567/test1/commits/56802f0ad5b1b3aa5c3e62b0164f3c644f6f7e5d/comments', 'author': {'login': 'ywang567', 'id': 35854285, 'avatar_url': 'https://avatars3.githubusercontent.com/u/35854285?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ywang567', 'html_url': 'https://github.com/ywang567', 'followers_url': 'https://api.github.com/users/ywang567/followers', 'following_url': 'https://api.github.com/users/ywang567/following{/other_user}', 'gists_url': 'https://api.github.com/users/ywang567/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ywang567/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ywang567/subscriptions', 'organizations_url': 'https://api.github.com/users/ywang567/orgs', 'repos_url': 'https://api.github.com/users/ywang567/repos', 'events_url': 'https://api.github.com/users/ywang567/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ywang567/received_events', 'type': 'User', 'site_admin': False}, 'committer': {'login': 'web-flow', 'id': 19864447, 'avatar_url': 'https://avatars3.githubusercontent.com/u/19864447?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/web-flow', 'html_url': 'https://github.com/web-flow', 'followers_url': 'https://api.github.com/users/web-flow/followers', 'following_url': 'https://api.github.com/users/web-flow/following{/other_user}', 'gists_url': 'https://api.github.com/users/web-flow/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/web-flow/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/web-flow/subscriptions', 'organizations_url': 'https://api.github.com/users/web-flow/orgs', 'repos_url': 'https://api.github.com/users/web-flow/repos', 'events_url': 'https://api.github.com/users/web-flow/events{/privacy}', 'received_events_url': 'https://api.github.com/users/web-flow/received_events', 'type': 'User', 'site_admin': False}, 'parents': []}
            ],
            [
                {'sha': 'bf9a7b9966db567819388a862d7528c3f48e31b7', 'commit': {'author': {'name': 'ywang567', 'email': '35854285+ywang567@users.noreply.github.com', 'date': '2018-02-09T17:43:24Z'}, 'committer': {'name': 'GitHub', 'email': 'noreply@github.com', 'date': '2018-02-09T17:43:24Z'}, 'message': 'Create rua', 'tree': 
                {'sha': '8f1a646fb2d3e2894df4f0cb5f4b802fbcd75a89', 'url': 'https://api.github.com/repos/ywang567/test2/git/trees/8f1a646fb2d3e2894df4f0cb5f4b802fbcd75a89'}, 'url': 'https://api.github.com/repos/ywang567/test2/git/commits/bf9a7b9966db567819388a862d7528c3f48e31b7', 'comment_count': 0, 'verification': {'verified': True, 'reason': 'valid', 'signature': '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJafd28CRBK7hj4Ov3rIwAAdHIIAET8MExyPklouvRnp6nTcz3g\nyD+wEcYhfjQ4ku1qs9FPFvKxoQLTIYg3hDZT+xovEiinCqAsEe66vW34ok7Gd1Kb\nlefVfzUg56jSqWML/BkyFRWq5Bzk+nXhEpHRcp7wky+eIQZ8tk2xDAfhDwhgYbZh\njIWyCDec7jY4/qiqBZNvlv1mn3+fTYt2y7DSfwTj61oCNomPuPUNgNnS8Tq7EGZy\nr+6Yml4r9xksg/GsFGxPxCErSTuSWGw8z//GMGI9Khu9cYZWMHDmGfnntJeUIlOx\nwpOWSuQIYgJ2Kna6FSqGYApCSdXTsfpJvxOvroFG56LibjQgE6c+Lioui6W9Q/w=\n=Lo21\n-----END PGP SIGNATURE-----\n', 'payload': 'tree 8f1a646fb2d3e2894df4f0cb5f4b802fbcd75a89\nparent a756bf7753708dc13a368dcb0f39fd454100bb09\nauthor ywang567 <35854285+ywang567@users.noreply.github.com> 1518198204 -0500\ncommitter GitHub <noreply@github.com> 1518198204 -0500\n\nCreate rua'}}, 'url': 'https://api.github.com/repos/ywang567/test2/commits/bf9a7b9966db567819388a862d7528c3f48e31b7', 'html_url': 'https://github.com/ywang567/test2/commit/bf9a7b9966db567819388a862d7528c3f48e31b7', 'comments_url': 'https://api.github.com/repos/ywang567/test2/commits/bf9a7b9966db567819388a862d7528c3f48e31b7/comments', 'author': {'login': 'ywang567', 'id': 35854285, 'avatar_url': 'https://avatars3.githubusercontent.com/u/35854285?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ywang567', 'html_url': 'https://github.com/ywang567', 'followers_url': 'https://api.github.com/users/ywang567/followers', 'following_url': 'https://api.github.com/users/ywang567/following{/other_user}', 'gists_url': 'https://api.github.com/users/ywang567/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ywang567/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ywang567/subscriptions', 'organizations_url': 'https://api.github.com/users/ywang567/orgs', 'repos_url': 'https://api.github.com/users/ywang567/repos', 'events_url': 'https://api.github.com/users/ywang567/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ywang567/received_events', 'type': 'User', 'site_admin': False}, 'committer': {'login': 'web-flow', 'id': 19864447, 'avatar_url': 'https://avatars3.githubusercontent.com/u/19864447?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/web-flow', 'html_url': 'https://github.com/web-flow', 'followers_url': 'https://api.github.com/users/web-flow/followers', 'following_url': 'https://api.github.com/users/web-flow/following{/other_user}', 'gists_url': 'https://api.github.com/users/web-flow/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/web-flow/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/web-flow/subscriptions', 'organizations_url': 'https://api.github.com/users/web-flow/orgs', 'repos_url': 'https://api.github.com/users/web-flow/repos', 'events_url': 'https://api.github.com/users/web-flow/events{/privacy}', 'received_events_url': 'https://api.github.com/users/web-flow/received_events', 'type': 'User', 'site_admin': False}, 'parents': [
                {'sha': 'a756bf7753708dc13a368dcb0f39fd454100bb09', 'url': 'https://api.github.com/repos/ywang567/test2/commits/a756bf7753708dc13a368dcb0f39fd454100bb09', 'html_url': 'https://github.com/ywang567/test2/commit/a756bf7753708dc13a368dcb0f39fd454100bb09'}]}, 
                {'sha': 'a756bf7753708dc13a368dcb0f39fd454100bb09', 'commit': {'author': {'name': 'ywang567', 'email': '35854285+ywang567@users.noreply.github.com', 'date': '2018-02-09T17:42:43Z'}, 'committer': {'name': 'GitHub', 'email': 'noreply@github.com', 'date': '2018-02-09T17:42:43Z'}, 'message': 'Initial commit', 'tree': 
                {'sha': 'afafad5ce3bcc5d0d47486eab9e6f072fab9e913', 'url': 'https://api.github.com/repos/ywang567/test2/git/trees/afafad5ce3bcc5d0d47486eab9e6f072fab9e913'}, 'url': 'https://api.github.com/repos/ywang567/test2/git/commits/a756bf7753708dc13a368dcb0f39fd454100bb09', 'comment_count': 0, 'verification': {'verified': True, 'reason': 'valid', 'signature': '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJafd2TCRBK7hj4Ov3rIwAAdHIIAJ/95VZLmVhLJcax5FxaJxFM\nx9KDrQr6ZTFU7p8jVVancFAY9NtjEhk0wPbsWbYaOaFm0jOLCmMd4wW0zPpsZ0bZ\nkbj3A9C33qvhiE8yooR/kUbpi4zg+4bnV5r1AfSKkS5dP/bQc2CzqIAZLdbPRWJq\nFSqdvG6QWUpoSXOH1j+r7bqQsmLq/PxhHyadasvXIXGrWmz/CWZDhS41PS03A+x2\nT7+yiUAk+3mwRI22KCkdMtJ30jApmiq7gGwXfOd/iXw05DoG3H2hWQUfhCMOLWAS\nb63k2ikMgKXtrH0+UsI2ySJ6pLPb7GtWq+J1stwUvo1pn+XpV01+Rxb6OASI4os=\n=Q6YZ\n-----END PGP SIGNATURE-----\n', 'payload': 'tree afafad5ce3bcc5d0d47486eab9e6f072fab9e913\nauthor ywang567 <35854285+ywang567@users.noreply.github.com> 1518198163 -0500\ncommitter GitHub <noreply@github.com> 1518198163 -0500\n\nInitial commit'}}, 'url': 'https://api.github.com/repos/ywang567/test2/commits/a756bf7753708dc13a368dcb0f39fd454100bb09', 'html_url': 'https://github.com/ywang567/test2/commit/a756bf7753708dc13a368dcb0f39fd454100bb09', 'comments_url': 'https://api.github.com/repos/ywang567/test2/commits/a756bf7753708dc13a368dcb0f39fd454100bb09/comments', 'author': {'login': 'ywang567', 'id': 35854285, 'avatar_url': 'https://avatars3.githubusercontent.com/u/35854285?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ywang567', 'html_url': 'https://github.com/ywang567', 'followers_url': 'https://api.github.com/users/ywang567/followers', 'following_url': 'https://api.github.com/users/ywang567/following{/other_user}', 'gists_url': 'https://api.github.com/users/ywang567/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ywang567/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ywang567/subscriptions', 'organizations_url': 'https://api.github.com/users/ywang567/orgs', 'repos_url': 'https://api.github.com/users/ywang567/repos', 'events_url': 'https://api.github.com/users/ywang567/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ywang567/received_events', 'type': 'User', 'site_admin': False}, 'committer': {'login': 'web-flow', 'id': 19864447, 'avatar_url': 'https://avatars3.githubusercontent.com/u/19864447?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/web-flow', 'html_url': 'https://github.com/web-flow', 'followers_url': 'https://api.github.com/users/web-flow/followers', 'following_url': 'https://api.github.com/users/web-flow/following{/other_user}', 'gists_url': 'https://api.github.com/users/web-flow/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/web-flow/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/web-flow/subscriptions', 'organizations_url': 'https://api.github.com/users/web-flow/orgs', 'repos_url': 'https://api.github.com/users/web-flow/repos', 'events_url': 'https://api.github.com/users/web-flow/events{/privacy}', 'received_events_url': 'https://api.github.com/users/web-flow/received_events', 'type': 'User', 'site_admin': False}, 'parents': []}
            ],
            [
                {'sha': 'a54977e9a7defe66a0a4fb2350024f3e6d3511f3', 'commit': {'author': {'name': 'ywang567', 'email': '35854285+ywang567@users.noreply.github.com', 'date': '2018-01-26T23:01:38Z'}, 'committer': {'name': 'GitHub', 'email': 'noreply@github.com', 'date': '2018-01-26T23:01:38Z'}, 'message': 'Initial commit', 'tree': 
                {'sha': '5ed70bc19b86d2c8cc43e528d55359bdde53816c', 'url': 'https://api.github.com/repos/ywang567/Triangle567/git/trees/5ed70bc19b86d2c8cc43e528d55359bdde53816c'}, 'url': 'https://api.github.com/repos/ywang567/Triangle567/git/commits/a54977e9a7defe66a0a4fb2350024f3e6d3511f3', 'comment_count': 0, 'verification': {'verified': True, 'reason': 'valid', 'signature': '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJaa7NSCRBK7hj4Ov3rIwAAdHIIAHcUmSkAWSPKFPazc89svfts\nxJvkRL61UgXT89NVtrVmOZsaT1o9z/VtgCSHGEspAPw+2BtUhNJPcMhaq2PPKsZE\nue0MGFGK/iV1ATCBJaqTOJmuXHmuGsyl2mSJ71bC0OdZwzN2mJmusx8rFaPa8z1/\nVP21OgjWf9L1/DCyN2ehnhOviyNoxjjFrQ71UjNepIvmACi13E0oLr8/Qjz7iLXV\n4UcZ76SVhZcCGzV3L3xfk9O2JKfrBgqwapcJtec2dvaPVUewnYHHTlFpO9xCIhx5\nD1Pl5xo629jMCpAW5ZdJBOF5Crxkhub1XKTkWiQc3eKMPm2rHH0goGEbAKfE1YQ=\n=gxCl\n-----END PGP SIGNATURE-----\n', 'payload': 'tree 5ed70bc19b86d2c8cc43e528d55359bdde53816c\nauthor ywang567 <35854285+ywang567@users.noreply.github.com> 1517007698 -0500\ncommitter GitHub <noreply@github.com> 1517007698 -0500\n\nInitial commit'}}, 'url': 'https://api.github.com/repos/ywang567/Triangle567/commits/a54977e9a7defe66a0a4fb2350024f3e6d3511f3', 'html_url': 'https://github.com/ywang567/Triangle567/commit/a54977e9a7defe66a0a4fb2350024f3e6d3511f3', 'comments_url': 'https://api.github.com/repos/ywang567/Triangle567/commits/a54977e9a7defe66a0a4fb2350024f3e6d3511f3/comments', 'author': {'login': 'ywang567', 'id': 35854285, 'avatar_url': 'https://avatars3.githubusercontent.com/u/35854285?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ywang567', 'html_url': 'https://github.com/ywang567', 'followers_url': 'https://api.github.com/users/ywang567/followers', 'following_url': 'https://api.github.com/users/ywang567/following{/other_user}', 'gists_url': 'https://api.github.com/users/ywang567/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ywang567/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ywang567/subscriptions', 'organizations_url': 'https://api.github.com/users/ywang567/orgs', 'repos_url': 'https://api.github.com/users/ywang567/repos', 'events_url': 'https://api.github.com/users/ywang567/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ywang567/received_events', 'type': 'User', 'site_admin': False}, 'committer': {'login': 'web-flow', 'id': 19864447, 'avatar_url': 'https://avatars3.githubusercontent.com/u/19864447?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/web-flow', 'html_url': 'https://github.com/web-flow', 'followers_url': 'https://api.github.com/users/web-flow/followers', 'following_url': 'https://api.github.com/users/web-flow/following{/other_user}', 'gists_url': 'https://api.github.com/users/web-flow/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/web-flow/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/web-flow/subscriptions', 'organizations_url': 'https://api.github.com/users/web-flow/orgs', 'repos_url': 'https://api.github.com/users/web-flow/repos', 'events_url': 'https://api.github.com/users/web-flow/events{/privacy}', 'received_events_url': 'https://api.github.com/users/web-flow/received_events', 'type': 'User', 'site_admin': False}, 'parents': []}
            ]
        ]
    
        response = get_commit_info()
        self.assertIsNotNone(response)
        self.assertIsInstance(response[0], list)

    def test_get_user_info(self):
        expected = ['User: ywang567',
                    'Repo: test1 Number of commits: 3',
                    'Repo: test2 Number of commits: 2',
                    'Repo: Triangle567 Number of commits: 1']
        self.assertEqual(get_user_info(), expected)


if __name__ == '__main__':
    unittest.main()

